# Generated by Django 3.1.1 on 2020-10-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='CLUB CITY'),
        ),
        migrations.AlterField(
            model_name='club',
            name='content',
            field=models.TextField(blank=True, verbose_name='CONTENT'),
        ),
        migrations.AlterField(
            model_name='club',
            name='location',
            field=models.CharField(max_length=50, verbose_name='MEETING PLACE'),
        ),
    ]
