# Generated by Django 3.1.1 on 2020-10-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyclediary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclediary',
            name='diary_dt',
            field=models.DateField(verbose_name='DIARY DATE'),
        ),
    ]
